export enum REQUEST_STATUS {
  SUCCESS = 200,
  BAD_INPUT = 400,
  FORBIDDEN = 403,
  CONNECTION_ERROR = 404,
  SERVER_ERROR = 500,
  UNKNOWN = 999,
}

export enum REQUEST_CODES {
  SUCCESS = 0,
  BAD_CREDENTIALS = 1,
  BAD_TOKEN = 2,
  NO_CONSENT = 3,
  TOKEN_SAVE = 4,
  TOKEN_RETRIEVE = 5,
  BAD_INPUT = 400,
  FORBIDDEN = 403,
  CONNECTION_ERROR = 404,
  SERVER_ERROR = 500,
  UNKNOWN = 999,
}
