name: build-ios

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    environment: build-ios

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get tag
        id: tag
        run: echo "::set-output name=tag::`git describe --tags`"

      - name: Install dependencies
        run: npm ci

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Paris"
          timezoneMacos: "Europe/Paris"

      - name: Install pod dependencies
        run: |
          cd ios && pod install

      - name: Build IOS App
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ios/Campus.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: ios/Campus.xcworkspace
          scheme: Campus

      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
